### ISSUE TITLE
Not working in Chrome on MacOS 10.13.6

### ISSUE THREAD

**Issue by edglazer** [wzub/goodreads_overdrive#1]
This looks like a super useful script (for me!), but it's not doing anything that I can see. I'm on the latest Chrome version (Version 69.0.3497.100 (Official Build) (64-bit)), and latest OS update for High Sierra. I tried to poke around the javascript console in Chrome to see if there were any error messages, but I wasn't able to see anything from the extension. Happy to help troubleshoot, if you tell me what you need me to do?

Thanks!

**Comment by wzub** [comment]
Hi there - thanks for the bug report! The script creates `<div id="GDratings">` and puts the icon and link in there. Can you please check if that div has been created once the page completes loading? Should be appended to `<div class="js-starRatingsContainer">`

**Comment by edglazer** [comment]
Thanks for getting back with me right away, sorry I didn't catch your response sooner!
I don't see the `<div id="GDratings">` anywhere in the code. The `<div class="js-starRatingsContainer">` is there, but no id attached. 

Let me know what else I can do to help troubleshoot this! I'm currently on a MacOS Sierra (10.12.6) installation in Chrome version 70.0.3538.77.

Thanks!

**Comment by wzub** [comment]
I think the code got stripped out of your reply. Could you confirm if you are looking at this on a library site on Overdrive (eg. https://brooklyn.overdrive.com/media/2546850?cid=218979) rather than just overdrive.com?

**Comment by edglazer** [comment]
Sorry about that, I edited the above entry with the appropriate code tags. 
And yes, I'm on a library site for overdrive. For an example:
[https://mlc.overdrive.com/mlc-capitalarea/content/media/1263727?cid=81428](https://mlc.overdrive.com/mlc-capitalarea/content/media/1263727?cid=81428)

I just searched the source and also looked in the developer console Page Sources and don't see a `id="GDratings"` anywhere. Thanks for the support on this!

**Comment by edglazer** [comment]
Just an update, I was looking at chrome extensions this morning and saw that there was a button for "Errors" next to "Details" and "Remove." CLicking on the errors button showed the following message:
"Unrecognized manifest key 'developer'."

and the following code was highlighted:

"developer": {
      "name": "Waleed Zuberi",
      "url": "https://waleedzuberi.com"
   },

not sure if that would be the problem?

**Comment by wzub** [comment]
Hi @edglazer, it's been a while since you reached out but in case you're interested I've made some updates and would love if you can take a look. Thanks!

**Comment by edglazer** [comment]
Hi @wzub I just check it, and it is 100% working for me now. Thank you!
